source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'YPBanner_Example', :exclusive => true do
  pod 'YPBanner', :path => '../'
  pod 'SDWebImage', '~> 3.7.3'
end

target 'YPBanner_Tests', :exclusive => true do
  pod 'YPBanner', :path => '../'
  pod 'SDWebImage', '~> 3.7.3'
end
