source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'YPBanner_Example', :exclusive => true do
  pod 'YPBanner', :path => '../'
end

target 'YPBanner_Tests', :exclusive => true do
  pod 'YPBanner', :path => '../'

  
end
